name: 'PyPI Package Health Check'
description: 'Check popularity, maintenance, and license issues for PyPI packages based on requirements.txt'
author: 'Your Name'
inputs:
  package_list_path:
    description: 'Path to the requirements.txt file'
    required: true
    default: 'requirements.txt'
  token:
    description: 'GitHub Token for API authentication'
    required: false
    default: '${{ github.token }}'
runs:
  using: 'node16'
  main: 'index.js'
