name: PyPI 패키지 건전성 점검!

on:
  workflow_dispatch:  
  push:
  
jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: PyPI 패키지 건전성 점검 실행
        uses: ./ 
        with:
          package_list_path: 'requirements.txt'
